### ISSUE TITLE
CI: Tests built w/ MingGW GCC segfault

### ISSUE THREAD

**Issue by ant2a** [accellera-official/cci#326]
The examples will segfault in the CI when built with MinGW GCC on Windows, which is why they are currently disabled.

When run in the CI (using the CMake "check" target), the tests segfault.
If the tests are then re-run by calling "ctest" directly, the tests pass without any problems.
```yml
- name: Test
  working-directory: ${{env.CCI_HOME}}/build
  run: |
    cmake --build ./examples --config Release --target check   # <- Tests segfault (Access violation)
    ctest --test-dir ./examples   # <- succeeds
```
Changing the shell from `Powershell` to `cmd.exe` did not help.

The problem does not occur when I run the "check" target manually over an SSH connection to the CI runner (using [mxschmitt/action-tmate](https://github.com/mxschmitt/action-tmate)). Unfortunately, I also cannot reproduce the issue on my machine.
